#!/usr/bin/env python3
"""
/etc/hosts manager for zen-brain (separate block markers from zen-platform).
Uses ZEN-BRAIN-MANAGED HOSTS so it does not collide with ZEN-MANAGED HOSTS.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile

_common_dir = os.path.dirname(os.path.abspath(__file__))
if _common_dir not in sys.path:
    sys.path.insert(0, _common_dir)
import config as _config  # noqa: E402

HOSTS_FILE = "/etc/hosts"
BLOCK_BEGIN = "# BEGIN ZEN-BRAIN-MANAGED HOSTS"
BLOCK_END = "# END ZEN-BRAIN-MANAGED HOSTS"
BLOCK_BEGIN_RE = re.compile(r"# BEGIN ZEN-BRAIN-MANAGED HOSTS\s+env=(\S+)")
BLOCK_END_RE = re.compile(r"# END ZEN-BRAIN-MANAGED HOSTS\s+env=(\S+)")


def _repo_root() -> str:
    return os.path.abspath(os.path.join(_common_dir, "..", ".."))


def _load_clusters(config_path: str | None) -> dict:
    out = {}
    for e in _config.list_envs(config_path):
        block = _config.get_cluster_block(e, config_path)
        domains = block.get("domains") or []
        if not isinstance(domains, list):
            domains = []
        out[e] = {"ip": (block.get("env_ip") or "").strip(), "domains": [str(d).strip() for d in domains]}
    return out


def _read_hosts(path: str) -> str:
    try:
        with open(path, encoding="utf-8") as f:
            return f.read()
    except PermissionError:
        r = subprocess.run(["cat", path], capture_output=True, text=True, timeout=5)
        if r.returncode == 0:
            return r.stdout or ""
        print("ERROR: Cannot read hosts file (permission denied)", file=sys.stderr)
        sys.exit(1)


def _parse(content: str) -> tuple[str, dict[str, list[tuple[str, str]]], str]:
    lines = content.splitlines()
    prefix = []
    blocks = {}
    suffix = []
    current_env = None
    current_entries = []
    i = 0
    while i < len(lines):
        line = lines[i]
        m_begin = BLOCK_BEGIN_RE.match(line.strip())
        if m_begin:
            env = m_begin.group(1)
            if current_env is not None:
                blocks[current_env] = current_entries
            current_env = env
            current_entries = []
            i += 1
            continue
        m_end = BLOCK_END_RE.match(line.strip())
        if m_end and current_env == m_end.group(1):
            blocks[current_env] = current_entries
            current_env = None
            current_entries = []
            i += 1
            continue
        if current_env is not None:
            stripped = line.strip()
            if stripped and not stripped.startswith("#"):
                parts = stripped.split(None, 1)
                if len(parts) >= 2:
                    current_entries.append((parts[0], parts[1]))
            i += 1
            continue
        prefix.append(line)
        i += 1
    if current_env is not None:
        blocks[current_env] = current_entries
    suffix = lines[len(prefix):]
    return "\n".join(prefix), blocks, "\n".join(suffix)


def _render_block(env: str, entries: list[tuple[str, str]]) -> str:
    sorted_entries = sorted(set(entries), key=lambda x: (x[0], x[1]))
    lines = [
        f"# BEGIN ZEN-BRAIN-MANAGED HOSTS env={env}",
        "# Generated by zen-brain scripts/common/hosts.py",
        "# DO NOT EDIT MANUALLY",
    ]
    for ip, domain in sorted_entries:
        lines.append(f"{ip} {domain}")
    lines.append(f"# END ZEN-BRAIN-MANAGED HOSTS env={env}")
    return "\n".join(lines) + "\n"


def _write_atomic(path: str, content: str, dry_run: bool) -> None:
    if dry_run:
        print(content, end="")
        return
    fd, tmp = tempfile.mkstemp(prefix="hosts.", dir=os.path.dirname(path), text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp, path)
        try:
            os.chmod(path, 0o644)
        except OSError:
            pass
    except Exception:
        os.unlink(tmp)
        raise


def cmd_apply(env: str, config_path: str | None, hosts_path: str, dry_run: bool) -> None:
    clusters = _load_clusters(config_path)
    if env not in clusters:
        print(f"ERROR: Unknown env '{env}'", file=sys.stderr)
        sys.exit(1)
    content = _read_hosts(hosts_path)
    prefix, blocks, suffix = _parse(content)
    ip = clusters[env]["ip"]
    domains = sorted(clusters[env]["domains"])
    blocks[env] = [(ip, d) for d in domains]
    envs_order = sorted(blocks.keys())
    out_lines = [prefix.rstrip()]
    for e in envs_order:
        if e in blocks and blocks[e]:
            if out_lines and not out_lines[-1].endswith("\n"):
                out_lines.append("")
            out_lines.append(_render_block(e, blocks[e]).rstrip())
    if suffix.strip():
        if out_lines and not out_lines[-1].endswith("\n"):
            out_lines.append("")
        out_lines.append(suffix.rstrip())
    full = "\n".join(out_lines) + "\n"
    _write_atomic(hosts_path, full, dry_run)
    if not dry_run:
        print("✓ /etc/hosts updated (zen-brain managed block)")


def cmd_remove(env: str, config_path: str | None, hosts_path: str, dry_run: bool) -> None:
    clusters = _load_clusters(config_path)
    content = _read_hosts(hosts_path)
    prefix, blocks, suffix = _parse(content)
    blocks.pop(env, None)
    envs_order = sorted(blocks.keys())
    out_lines = [prefix.rstrip()]
    for e in envs_order:
        if e in blocks and blocks[e]:
            if out_lines and not out_lines[-1].endswith("\n"):
                out_lines.append("")
            out_lines.append(_render_block(e, blocks[e]).rstrip())
    if suffix.strip():
        if out_lines and not out_lines[-1].endswith("\n"):
            out_lines.append("")
        out_lines.append(suffix.rstrip())
    full = "\n".join(out_lines) + "\n"
    _write_atomic(hosts_path, full, dry_run)
    if not dry_run:
        print("✓ /etc/hosts updated (removed zen-brain block for env)")


def cmd_verify(env: str, config_path: str | None, hosts_path: str) -> int:
    import socket
    clusters = _load_clusters(config_path)
    if env not in clusters:
        print(f"ERROR: Unknown env '{env}'", file=sys.stderr)
        return 1
    content = _read_hosts(hosts_path)
    hosts_map = {}
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(None, 1)
        if len(parts) < 2:
            continue
        for domain in parts[1].split():
            if domain.startswith("#"):
                break
            hosts_map[domain] = parts[0]
    expected_ip = clusters[env]["ip"]
    failed = False
    for domain in clusters[env]["domains"]:
        resolved = None
        try:
            resolved = socket.gethostbyname(domain)
        except socket.gaierror:
            resolved = hosts_map.get(domain)
        if resolved == expected_ip:
            print(f"PASS {domain} -> {resolved}")
        else:
            print(f"FAIL {domain} expected={expected_ip} got={resolved or 'N/A'}")
            failed = True
    if failed:
        print("HOSTS_VERIFY_FAIL", file=sys.stderr)
        return 1
    print("HOSTS_VERIFY: PASS")
    return 0
