// Package messagebus provides the generic pub/sub interface for event distribution.
// The message bus is the nervous system that connects Office and Factory components,
// enabling reliable, at-least-once delivery with deduplication.
//
// Implementation uses Redis Streams as the backbone, with zen-sdk/pkg/dedup
// for duplicate suppression.
package messagebus

import (
	"context"
	"time"
)

// Event represents a message bus event.
type Event struct {
	// ID is the stream entry ID (auto-generated by Redis).
	ID string `json:"id"`

	// Type is the event type (e.g., "work_item.created", "intent.analyzed").
	Type string `json:"type"`

	// Source identifies the producer (e.g., "jira-connector", "intent-analyzer").
	Source string `json:"source"`

	// Correlation links related events (e.g., session ID, task ID).
	Correlation string `json:"correlation"`

	// Payload is the encoded event data (JSON, Protobuf, etc.).
	Payload []byte `json:"payload"`

	// Metadata contains additional headers (e.g., tracing IDs, tenant, cluster).
	Metadata map[string]string `json:"metadata"`

	// Timestamp is when the event was created (producer clock).
	Timestamp time.Time `json:"timestamp"`
}

// Subscription represents an active subscription to a stream.
type Subscription interface {
	// Events returns a channel of incoming events.
	Events() <-chan *Event

	// Errors returns a channel of subscription errors.
	Errors() <-chan error

	// Close closes the subscription and releases resources.
	Close() error
}

// MessageBus defines the generic pub/sub interface for event distribution.
type MessageBus interface {
	// Publish publishes an event to a stream.
	// If the stream does not exist, it is created automatically.
	Publish(ctx context.Context, stream string, event *Event) error

	// Subscribe creates a subscription to a stream.
	// If group is empty, a unique consumer group is created.
	// The consumer name is auto-generated if empty.
	Subscribe(ctx context.Context, stream, group, consumer string) (Subscription, error)

	// CreateConsumerGroup creates or ensures a consumer group exists.
	// If stream does not exist, it is created with zero length.
	CreateConsumerGroup(ctx context.Context, stream, group string) error

	// Ack acknowledges successful processing of an event.
	// The event is removed from the pending entries list for this consumer group.
	Ack(ctx context.Context, stream, group, id string) error

	// Pending returns pending events for a consumer group.
	Pending(ctx context.Context, stream, group string) ([]*Event, error)

	// Close closes the connection and releases all resources.
	Close() error
}

// DedupConfig holds deduplication configuration.
type DedupConfig struct {
	// WindowSeconds is the deduplication window per source.
	WindowSeconds int64 `json:"window_seconds"`

	// MaxEntries is the maximum number of deduplication entries to keep.
	MaxEntries int64 `json:"max_entries"`

	// Enabled enables deduplication (default: true).
	Enabled bool `json:"enabled"`
}