apiVersion: apps/v1
kind: Deployment
metadata:
  name: zen-lock-controller
  namespace: zen-lock-system
  labels:
    app.kubernetes.io/name: zen-lock-controller
    app.kubernetes.io/part-of: zen-lock
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zen-lock-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zen-lock-controller
        app.kubernetes.io/part-of: zen-lock
    spec:
      serviceAccountName: zen-lock-controller
      containers:
      - name: manager
        image: zen-lock/zen-lock:v0.0.3-alpha
        imagePullPolicy: IfNotPresent
        args:
          - --zap-level=info
          - --zap-encoder=json
          - --metrics-bind-address=:8080
          - --leader-election
          - --health-probe-bind-address=:8081
          - --controller-runtime
        env:
          - name: ZEN_LOCK_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: key.txt
          - name: ZEN_LOCK_WEBHOOK_TIMEOUT
            value: "30s"
        ports:
          - name: webhook
            containerPort: 9443
          - name: metrics
            containerPort: 8080
          - name: health
            containerPort:  8081
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Deployment
metadata:
  name: zen-lock-webhook
  namespace: zen-lock-system
  labels:
    app.kubernetes.io/name: zen-lock-webhook
    app.kubernetes.io/part-of: zen-lock
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zen-lock-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zen-lock-webhook
        app.kubernetes.io/part-of: zen-lock
    spec:
      serviceAccountName: zen-lock-webhook
      containers:
      - name: webhook
        image: zen-lock/zen-lock:v0.0.3-alpha
        imagePullPolicy: IfNotPresent
        args:
          - --zap-level=info
          - --zap-encoder=json
          - --webhook-only
          - --webhook-tls-cert-dir=/var/run/webhook/certs
          - --webhook-tls-host=0.0.0.0
          - --webhook-tls-port=9443
        env:
          - name: ZEN_LOCK_WEBHOOK_TIMEOUT
            value: "30s"
        ports:
          - name: webhook
            containerPort: 9443
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
